# Generated by Django 5.1 on 2024-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('status', models.BooleanField()),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
