# Generated by Django 5.1 on 2024-08-26 16:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclePost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.postmodel',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
