# Generated by Django 4.2.16 on 2024-12-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='likes',
        ),
    ]
